name = "Basic_01"
uuid = "0551298f-836a-4b29-ad35-01a0c4ab200c"
version = "0.1.0"
authors = ["Cody Tapscott <topolarity@tapscott.me>"]

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Statistics = "1.11.1"
